CREATE OR REPLACE TRIGGER empl_examination_salary
BEFORE
INSERT OR UPDATE ON emplyees
FOR EACH ROW
DECLARE
excep EXCEPTION;
BEGIN
IF INSERTING OR UPDATING THEN
    IF MOD (:NEW.SALARY, 100) <> 0 AND :NEW.SALARY IS NOT NULL THEN
        RAISE excep;
    END IF;
END IF;
EXCEPTION
WHEN excep THEN
    RAISE_APPLICATION_ERROR(-20000, 'Зарплата не кратна 100!!');
END;